config/routes.rb
CosmosApp::Application.routes.draw do

   root 'welcome#index'
   match '/signup',       to: 'users#new',                via: 'get'
   match '/signin',       to: 'sessions#new',             via: 'get'
   match '/show',         to: 'users#show',                via: 'get'
   match '/signout',      to: 'sessions#destroy',         via: 'delete'
   match '/transactions', to: 'users#transactions',       via: 'post'
   match '/charges',      to: 'charges#new',              via: 'get'
   match '/refund',       to: 'users#refund',             via: 'post'
   match '/refresh',      to: 'users#refresh',            via: 'post'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :charges

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", '#' %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoSite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
<%= yield %>
<%#= debug(params) %>
</body>
</html>